# Generated by Django 3.2.6 on 2021-10-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_ingredients_ingredientstag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='Tag',
            field=models.ManyToManyField(blank=True, to='backend.IngredientsTag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='backend.ProductImage'),
        ),
    ]
